Lr3 done
AshRaven521/ITiROD pull request #2
Opened 2022-04-28 19:57 UTC by AshRaven521

https://ashraven521.github.io/ITiROD/

2022-04-30 08:58 UTC, Nastik1811 commented
А почему у вас вроде есть отдельные страницы, но то же самое дублируется в модалках?
<img width="296" alt="image" src="https://user-images.githubusercontent.com/37243282/166099041-322deb0d-04fa-4d65-9145-f7a23c0041f4.png">

2022-04-30 09:44 UTC, AshRaven521 commented
Изнаяально хотел сделать можальные окна в отдельных страницах, а заьем подключить в основной файл
Но не получилось, не фортануло
А удалять было лень)
Если это важно, то удалю

2022-04-30 11:47 UTC, Nastik1811 commented
В идеале, по крайней мере страница с историей поиска, должна быть отдельной страницей (грубо говоря, чтобы в адресной строке менялся url при переходе на неё). На этапе 3 лабы это можно было сделать отдельными html'ками, в которых просто дублируются header/footer, но основное содержимое разное, а потом уже, в следующей лабе, из этого делается spa средствами js (в результате у вас будет снова одна html, а контент при навигации будет меняться js'ом)

2022-04-30 12:01 UTC, Nastik1811 commented on Scripts/modal_scripts.js
> +function openModalWindow(){
А где вы нашли такое решение для добавления обработчиков событий?

2022-04-30 12:01 UTC, Nastik1811 commented on README.md
> -4. Просмотр допольнительной информации о месте прибытия
![image](https://user-images.githubusercontent.com/37243282/166104620-69ead48a-e4bc-4769-95db-ee2a09bd6784.png)

2022-04-30 12:08 UTC, AshRaven521 commented on Scripts/modal_scripts.js
> +function openModalWindow(){
А что с этим решением не так?

2022-04-30 12:10 UTC, Nastik1811 commented on Scripts/modal_scripts.js
> +function openModalWindow(){
Собственно, в нём и причина того, что кнопки срабатывают со второго раза

2022-04-30 12:11 UTC, Nastik1811 commented on Scripts/modal_scripts.js
> +function openModalWindow(){
У вас ещё с модалками проблема, что можно открыть сразу несколько и они будут перекрывать друг друга

2022-04-30 12:41 UTC, Nastik1811 requested changes
С историей поиска и модалками можно в следующей лабе разобраться. Пока что нужно поправить остальные комментарии и сделать модальные окна чуть больше. 

И если не лень, добавьте модальным окнам обёртку в `div class="modal-container"` с примерно такими стилями

```
modal-container {
    display: grid;
    place-items: center;
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: rgb(245 245 245 / 10%);
    backdrop-filter: blur(6px);
}
``` 
Атрибуты `data-modal` (если он нужен будет) и `id` будут уже на этих контейнерах висеть тогда

2022-04-30 16:59 UTC, AshRaven521 commented on Scripts/modal_scripts.js
> +function openModalWindow(){
Исправил открытие модалки с первого раза

2022-04-30 17:08 UTC, AshRaven521 commented
> С историей поиска и модалками можно в следующей лабе разобраться. Пока что нужно поправить остальные комментарии и сделать модальные окна чуть больше.
> 
> И если не лень, добавьте модальным окнам обёртку в `div class="modal-container"` с примерно такими стилями
> 
> ```
> modal-container {
>     display: grid;
>     place-items: center;
>     position: fixed;
>     top: 0;
>     bottom: 0;
>     left: 0;
>     right: 0;
>     background-color: rgb(245 245 245 / 10%);
>     backdrop-filter: blur(6px);
> }
> ```
> 
> Атрибуты `data-modal` (если он нужен будет) и `id` будут уже на этих контейнерах висеть тогда

Исправил модальные окна: теперь открываются с первого раза и нельзя открыть несколько сразу(добавил modal-container), но не переносил data-modal и id, т.к. не работает.
Добавил к label атрибут for и к нужным input атрибут id.
Сделал модальные окна немного больше(90%).

Историю поиска не трогал(думаю в следующей лабораторной)

2022-05-02 16:47 UTC, Nastik1811 approved these changes
Ладно, так и быть, принято )

2022-05-02 16:47 UTC, Nastik1811 commented on modal-window.css
> +  visibility: hidden;
backdrop-filter не понравился? 🙂

2022-05-02 16:48 UTC, AshRaven521 commented on modal-window.css
> +  visibility: hidden;
А, там пока исправлял, он куда-то исчез)

2022-05-02 16:49 UTC, AshRaven521 commented
> Ладно, так и быть, принято ) 

Спасибо

2022-05-02 16:49 UTC, AshRaven521 commented on modal-window.css
>      max-width: 500px;
Поправлю

2022-05-02 16:59 UTC, merged